name: Rust CI/CD

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_path: target/release/scrolled-quran
          - os: ubuntu-latest
            artifact_path: target/release/scrolled-quran
          - os: windows-latest
            artifact_path: target/release/scrolled-quran.exe

    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
      
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update -y && sudo apt install -y pkg-config clang libwayland-dev libxkbcommon-x11-dev libvulkan-dev libfontconfig1-dev

    - uses: Swatinem/rust-cache@v2

    - name: Build release
      run: cargo build --release --verbose

    - uses: actions/upload-artifact@v6
      with:
        name: ${{ matrix.os }}
        path: ${{ matrix.artifact_path }}
        compression-level: 9
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v6    
    - uses: actions/download-artifact@v7
      with:
        path: artifacts
    
    - name: Display structure
      run: ls -R artifacts
    
    - name: Re-Tag preview
      run: gh release delete preview --yes || true
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Compress artifacts
      run: |
        cd artifacts
        mkdir compressed
        cd compressed
        zip -j -9 scrolled-quran-aarch64-aarch64-apple-darwin.zip ../macos-latest/scrolled-quran
        tar -cf scrolled-quran-x86_64-unknown-linux-gnu.tar.xz -I 'xz -9' ../ubuntu-latest/scrolled-quran
        zip -j -9 scrolled-quran-x86_64-pc-windows-msvc.zip ../windows-latest/scrolled-quran.exe

    - name: Display structure
      run: ls -R artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: preview
        name: Scrolled Quran Preview
        draft: false
        prerelease: true
        files: artifacts/compressed/*